<?php

/**
 * Returns addressfield_id_get_administrative_areas().
 */
function addressfield_id_get_administrative_areas() {
  $administrative_areas = array(
    1 => t('Bali'),
    2 => t('Bangka Belitung'),
    3 => t('Banten'),
    4 => t('Bengkulu'),
    5 => t('DI Yogyakarta'),
    6 => t('DKI Jakarta'),
    7 => t('Gorontalo'),
    8 => t('Jambi'),
    9 => t('Jawa Barat'),
    10 => t('Jawa Tengah'),
    11 => t('Jawa Timur'),
    12 => t('Kalimantan Barat'),
    13 => t('Kalimantan Selatan'),
    14 => t('Kalimantan Tengah'),
    15 => t('Kalimantan Timur'),
    16 => t('Kalimantan Utara'),
    17 => t('Kepulauan Riau'),
    18 => t('Lampung'),
    19 => t('Maluku'),
    20 => t('Maluku Utara'),
    21 => t('Nanggroe Aceh Darussalam (NAD)'),
    22 => t('Nusa Tenggara Barat (NTB)'),
    23 => t('Nusa Tenggara Timur (NTT)'),
    24 => t('Papua'),
    25 => t('Papua Barat'),
    26 => t('Riau'),
    27 => t('Sulawesi Barat'),
    28 => t('Sulawesi Selatan'),
    29 => t('Sulawesi Tengah'),
    30 => t('Sulawesi Tenggara'),
    31 => t('Sulawesi Utara'),
    32 => t('Sumatera Barat'),
    33 => t('Sumatera Selatan'),
    34 => t('Sumatera Utara'),
  );

  return $administrative_areas;
}
